### ISSUE TITLE
Mac OS M1: Add sub-dependencies

### ISSUE THREAD

**Issue by mohanish2504** [keephq/keep#649] opened 2023-12-24 16:31 UTC
Sqlalchemy has sub dependency to greenlet.

**To Reproduce**
just poetry install (1.3.2) mac m1 silicon

**Expected behavior**
Will fail with error 

`HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out`

**Desktop (please complete the following information):**
 - OS: Macbook M1 pro

Proposed fix:
- adding greenlet and grpcio to poetry fixes the issue.

**Comment by shahargl** [comment] 2023-12-24 16:32
hey @mohanish2504, can you elaborate a little bit? we do have docker image for M1.
do you run Keep in air-gapped environment?

**Comment by mohanish2504** [comment] 2023-12-24 16:34
Hey @shahargl what by air-gapped environment?

I was dev docker-compose file and was trying to build on local.

**Comment by shahargl** [comment] 2023-12-24 16:35
like without connectivity to the internet. But I think that if you are not sure - then its not that :P

So you've just ran `docker-compose -f docker-compose.dev.yml up` and got 
`HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out`
?

**Comment by mohanish2504** [comment] 2023-12-24 16:42
Yep. 
I have a good network bandwidth. 

I first thaught the same but after some digging, I realized there are separate issues for Mac M1 specifically.

references:
- https://github.com/sqlalchemy/sqlalchemy/issues/8181
- https://github.com/python-poetry/poetry/issues/5429#issuecomment-1263535230 ( This worked )
- https://github.com/grpc/grpc/issues/31737 

Note: even though issues are closed, I was able to reproduce it.

**Comment by mohanish2504** [comment] 2023-12-24 16:45
Fixed for me:
`
greenlet = "^3.0.3"
grpcio = "^1.60.0"
`
Not sure how to distribute while building for m1 and other systems and add dependency during runtime.
I think you must be having image at your hand only?

**Comment by shahargl** [comment] 2023-12-24 16:46
Super weird. I've M1 also and I'm trying to reproduce the problem. Do you want to open PR with the solution that have worked for you? I'll check it and merge it.

**Comment by mohanish2504** [comment] 2023-12-24 16:46
okay sure.

**Comment by shahargl** [comment] 2023-12-24 16:56
@mohanish2504 btw are you working with Keep now?

**Comment by shahargl** [comment] 2023-12-24 17:05
while working the reproduce it I found another bug (?) which fixed by this https://github.com/keephq/keep/pull/650

**Comment by mohanish2504** [comment] 2023-12-24 18:18
@shahargl it's indeed the poor connectivity. It seems the bandwidth was fluctuating quite a bit. 

Everything worked fine as soon as I moved back to my home network, was out 😅.
It was 10-12 Mbps constant though. 

You can mark this as closed.

**Comment by mohanish2504** [comment] 2023-12-24 18:18
I was able to reproduce the issue you fixed at #650

**Comment by mohanish2504** [comment] 2023-12-24 18:20
> @mohanish2504 btw are you working with Keep now?

Yes, definitely. 
Always looking forward to learn from OSS projects 😃.

**Comment by talboren** [comment] 2023-12-25 08:38
Closing this issue since it seems like it was just some internet connectivity problem :)

**Closed by talboren** 2023-12-25 08:38 UTC
Labels: wontfix
