### ISSUE TITLE
auto-deletion of resolved alerts

### ISSUE THREAD

**Issue by momoadc** [keephq/keep#691] opened 2024-01-07 14:42 UTC
**Is your feature request related to a problem? Please describe.**
QOL

**Describe the solution you'd like**
automated deletion of resolved alerts

**Comment by talboren** [comment] 2024-01-07 14:50
@momoadc I'm closing this one as it seems to be a duplicate of: https://github.com/keephq/keep/issues/654

**Closed by talboren** 2024-01-07 14:50 UTC
