### ISSUE TITLE
[🐛 Bug] Providers page crashes when using PostgreSQL due to bad datetime formatting

### ISSUE THREAD

**Issue by thomas-chauvet** [keephq/keep#1300] opened 2024-06-27 08:12 UTC
**Describe the bug**

The providers page display a KPI of the number of alerts for each integration. This KPI comes from the result of a query in the DB. When using postgres, the datetime formatting is wrong and make the query crashed. Thus, the providers page is not displayed due to crash in the backend.

**To Reproduce**

- Use postgresql DB
- create an integration
- generate an alert

**Expected behavior**

Should not crash

**Additional context**

I've opened a PR -> https://github.com/keephq/keep/pull/1299.

**Comment by shahargl** [comment] 2024-06-27 08:14
Hey @thomas-chauvet, thanks for opening the issue. I’ve solved this issue two days ago, can you pull the latest api image and retry?

**Comment by thomas-chauvet** [comment] 2024-06-27 08:33
Is it the one with tag `v0.17.0`?

Could you point me to the commit fix? I've tested with the main branch locally and it does not work.

**Comment by thomas-chauvet** [comment] 2024-06-27 09:09
@shahargl if you reference to this commit: https://github.com/keephq/keep/commit/9cb5b3535d40c3fd02285bda9868a5ef11a02659, it is not fixing the bug because:

- it appears at two places in the code
- as mentioned in my PR, [postgres needs a specific formatting](https://www.postgresql.org/docs/current/functions-formatting.html) and not the classic python formatting (e.g. `%Y`, etc. but `YYYY` etc.)

**Comment by shahargl** [comment] 2024-06-27 09:15
Are you sure? Since I’ve checked my self and with the user who raised the bug and it worked for both of us. Do you have a way to reproduce the bug?

**Comment by thomas-chauvet** [comment] 2024-06-27 09:53
Yes, I am pretty sure.

Here is a `docker-compose.yml` with the latest docker images:

```docker-compose.yml
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: keepuser
      POSTGRES_PASSWORD: keeppassword
      POSTGRES_DB: keepdb
    ports:
      - "5432:5432"

  keep-frontend:
    image: us-central1-docker.pkg.dev/keephq/keep/keep-ui:latest
    environment:
      - NEXTAUTH_SECRET=secret
      - NEXTAUTH_URL=http://localhost:3000
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - POSTHOG_KEY=phc_muk9qE3TfZsX3SZ9XxX52kCGJBclrjhkP9JxAQcm1PZ
      - POSTHOG_HOST=https://app.posthog.com
      - PUSHER_HOST=localhost
      - PUSHER_PORT=6001
      - PUSHER_APP_KEY=keepappkey
      - NEXT_PUBLIC_KEEP_VERSION=0.2.9
      - AUTH_TYPE=NO_AUTH
      - API_URL=http://keep-backend:8080
    depends_on:
      - keep-backend
    ports:
      - "3000:3000"

  keep-backend:
    image: us-central1-docker.pkg.dev/keephq/keep/keep-api:latest
    environment:
      - PORT=8080
      - SECRET_MANAGER_TYPE=FILE
      - SECRET_MANAGER_DIRECTORY=/state
      - PUSHER_APP_ID=1
      - PUSHER_APP_KEY=keepappkey
      - PUSHER_APP_SECRET=keepappsecret
      - PUSHER_HOST=keep-websocket-server
      - PUSHER_PORT=6001
      - USE_NGROK=false
      - AUTH_TYPE=NO_AUTH
      - DATABASE_CONNECTION_STRING=postgresql://keepuser:keeppassword@postgres:5432/keepdb
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  keep-websocket-server-common:
    image: quay.io/soketi/soketi:1.4-16-debian
    ports:
      - "6001:6001"
      - "9601:9601"
    environment:
      - SOKETI_USER_AUTHENTICATION_TIMEOUT=3000
      - SOKETI_DEBUG=1
      - SOKETI_DEFAULT_APP_ID=1
      - SOKETI_DEFAULT_APP_KEY=keepappkey
      - SOKETI_DEFAULT_APP_SECRET=keepappsecret
```

Launch docker compose:

```bash
docker compose up -d
```

Everything looks fine in the logs and [localhost:3000](http://localhost:3000/providers) is up and running.

Insert an alert:

```bash
PGPASSWORD=keeppassword \
  psql \
    -h localhost \
    -p 5432 \
    -U keepuser \
    -d keepdb
```

Insert:

```sql
INSERT INTO 
    public.alert (timestamp, event, id, tenant_id, fingerprint, alert_hash, provider_type)
VALUES ('2024-06-27 09:07:12.765000', '{"id": "TestAlert", "status": "firing", "severity": "critical"}', '749650c6-f264-40ae-95ae-6d1469a19929', 'keep',  'dc127765e7d5c047', '696f231f048cb1fba3428d28c4b77da4216ea4c5607316824cf7d22bbe4e9038', 'prometheus');
```

Check the alert:

```sql
SELECT * FROM public.alert;
```

[localhost:3000](http://localhost:3000/providers) is failing. We can see the error concerning the datetime format in the api logs:

```txt
  File "/venv/lib/python3.11/site-packages/keep/api/routes/providers.py", line 74, in get_providers
    providers_distribution = get_provider_distribution(tenant_id)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/keep/api/core/db.py", line 1621, in get_provider_distribution
    time = datetime.strptime(time, time_format)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '%4-%m-%5 %H' does not match format '%Y-%m-%d %H'
```

**Comment by talboren** [comment] 2024-06-27 12:32
@thomas-chauvet is it correct that #1299 closed this issue?

**Comment by shahargl** [comment] 2024-06-27 13:04
I've merged https://github.com/keephq/keep/pull/1299

Thanks @thomas-chauvet 👑

**Closed by shahargl** 2024-06-27 13:04 UTC
