### ISSUE TITLE
multi-tenancy for keep

### ISSUE THREAD

**Issue by momoadc** [keephq/keep#658] opened 2023-12-27 08:15 UTC
**Is your feature request related to a problem? Please describe.**
QOL

**Describe the solution you'd like**
A multi-tenancy solution for keep, My idea is to only show alerts to users based on labels, so user X will only have access to alerts with label X and so on.
perhaps also link certain providers with certain users.

this is a way to aggregate all alerts in one keep instance for NOC purposes and also allow individual teams to use the platform in order to manage their own alerts if needed

**Comment by talboren** [comment] 2023-12-27 08:26
Thank you for the issue @momoadc!

We're working on a few issues related with what you just purposed (https://github.com/keephq/keep/issues/656 and https://www.keycloak.org/ as part of it and a few others).

While it is not that progressive as you just mentioned, could the "Presets" feature help you with some of the things you require?
![CleanShot 2023-12-27 at 10 26 17](https://github.com/keephq/keep/assets/68807791/637aa6ab-d026-4c99-9d48-d548927be41f)

**Comment by talboren** [comment] 2024-02-11 13:24
Closing as it's a duplicate of #656 which @shahargl already works on.

**Closed by talboren** 2024-02-11 13:24 UTC
Labels: API, Infrastructure
